# Landslide Data Exploration

In [2]:
import geopandas as gpd

# Path to the shapefile
shapefile_path = r"C:\Art_of_Coding\visionbased_grp\-Vision-Based-Landslide-Forecasting-Using-Satellite-Imagery\Landslides\SHP"

# Load the data
gdf = gpd.read_file(shapefile_path)

print(f"Total landslide records: {len(gdf)}")
print(f"CRS: {gdf.crs}")

# Show first 5 rows
gdf.head()

Total landslide records: 4225
CRS: EPSG:4326

   Id                                           geometry
0   0  POLYGON ((80.42449 7.75369, 80.42449 7.75371, ...
1   0  POLYGON ((80.51753 7.71014, 80.51753 7.71012, ...
2   0  POLYGON ((80.51803 7.71148, 80.51803 7.7115, 8...
3   0  POLYGON ((80.5204 7.71311, 80.52038 7.71314, 8...
4   0  POLYGON ((80.88291 7.63879, 80.88287 7.63875, ...

In [3]:
# Convert to Geographic Coordinates (Latitude and Longitude)
if gdf.crs != "EPSG:4326":
    gdf = gdf.to_crs("EPSG:4326")

# Get the center point (centroid) of each polygon
import warnings
warnings.filterwarnings("ignore", category=UserWarning) # Ignore the centroid warning

gdf['centroid'] = gdf.geometry.centroid
gdf['longitude'] = gdf['centroid'].x
gdf['latitude'] = gdf['centroid'].y

# Display the coordinates
gdf[['longitude', 'latitude']].head()

   longitude  latitude
0  80.424816  7.753966
1  80.516997  7.710134
2  80.518396  7.711988
3  80.520509  7.713424
4  80.882740  7.639323